# Generated by Django 5.0.6 on 2024-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(choices=[('Mobile Recharge', 'Mobile Recharge'), ('DTH Recharge', 'DTH Recharge'), ('Insurance payment', 'Insurance payment')], max_length=50)),
                ('mode_of_payment', models.CharField(choices=[('UPI', 'UPI'), ('Internet banking', 'Internet banking'), ('Card payment', 'Card payment')], max_length=50)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('current_date', models.DateField(auto_now=True)),
                ('service', models.ManyToManyField(related_name='subscription', to='mini_payment.service')),
                ('user', models.ManyToManyField(related_name='user_subscription', to='mini_payment.serviceuser')),
            ],
        ),
    ]
