# Generated by Django 5.0.6 on 2024-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
